name: shared
description: Shared is a free and open-source app that lets you create multiple projects, add and track expenses, split expenses unevenly between members, and settle up balances between group members. It's a great alternative to other expense tracking apps, especially for groups who need to manage expenses together.

publish_to: 'none'

version: 0.2.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.4+1
  path: ^1.8.2
  flow_builder: ^0.0.9
  select_form_field: ^2.2.0
  shared_preferences: ^2.0.18
  flutter_slidable: ^2.0.0
  pocketbase: ^0.7.3
  intl: ^0.18.0
  dynamic_color: ^1.6.2
  tuple: ^2.0.1
  share_plus: ^6.3.1
  flutter_speed_dial: ^6.2.0
  app_links: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#e53735"
  adaptive_icon_foreground: "assets/icons/icon.png"